# Generated by Django 4.1.3 on 2022-11-10 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_newspaper_options_alter_redactor_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newspaper",
            options={"ordering": ["-published_date"]},
        ),
    ]
