# Generated by Django 4.1.3 on 2022-11-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_newspaper_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="redactor",
            name="workplace",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
